### ISSUE TITLE
Globo.TV na Raspberry PI

### ISSUE THREAD

**Issue by erduarte** [vitorhirota/plugin.video.globotv#8]
Caro Vitor, estou tentando rodar o addon globo.TV na raspberry. Ela esta portando a última versão do OpenElec com o XBMC. O addon é instalado normalmente e as opções também são listadas porém quando tento rodar qualquer vídeo é apresentado um erro de script. Consultei o log do xbmc e copio abaixo para talvez ajuda-lo a identificar o problema. Também gostaria de obter informações de como aprender sobre programação destes Addons e também contribuir já que também sou programador. Parabéns pelo trabalho e se puder me dar mais informações deste addon na raspberry agradeço.
Abaixo segue log. Caso precise de mais alguma informação do sistema me oriente que lhe envio!
Abraço
Eduardo Duarte

11:15:46 T:2786137184  NOTICE: -->Python Interpreter Initialized<--
11:15:53 T:2786137184  NOTICE: [xbmcswift2] Request for "/play/1797790" matches rule for function "play"
11:15:56 T:2786137184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name constants
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.globotv-master/addon.py", line 169, in <module>
                                                plugin.run()
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/.xbmc/addons/plugin.video.globotv-master/addon.py", line 56, in play
                                                videos = api.get_videos(vid)
                                              File "/storage/.xbmc/addons/plugin.video.globotv-master/resources/lib/globo.py", line 206, in get_videos
                                                data = self._get_video_info(video_id)
                                              File "/storage/.xbmc/addons/plugin.video.globotv-master/resources/lib/globo.py", line 85, in _get_video_info
                                                data = self._get_cached(INFO_URL % video_id)['videos'][0]
                                              File "/storage/.xbmc/addons/plugin.video.globotv-master/resources/lib/globo.py", line 53, in _get_cached
                                                and json.loads(r.text) or r.text)
                                              File "/storage/.xbmc/addons/script.module.requests/lib/requests/models.py", line 577, in text
                                                encoding = self.apparent_encoding
                                              File "/storage/.xbmc/addons/script.module.requests/lib/requests/models.py", line 482, in apparent_encoding
                                                return chardet.detect(self.content)['encoding']
                                              File "/storage/.xbmc/addons/script.module.requests/lib/requests/packages/charade/__init__.py", line 22, in detect
                                                from . import universaldetector
 File "/storage/.xbmc/addons/script.module.requests/lib/requests/packages/charade/universaldetector.py", line 29, in <modu$
                                                from . import constants
                                            ImportError: cannot import name constants
                                            -->End of Python script error report<--
11:15:56 T:3045372880   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.globotv/play/1797790]
11:16:01 T:2786137184  NOTICE: Thread BackgroundLoader start, auto delete: false
11:18:42 T:2786137184  NOTICE: Thread XBPyThread start, auto delete: false
11:18:42 T:2786137184  NOTICE: -->Python Interpreter Initialized<--
11:18:49 T:2786137184  NOTICE: [xbmcswift2] Request for "/rede-globo/globo-reporter/4dff96df96bfbb284500001c" matches rule for function "list_rail_videos"
11:18:50 T:2786137184 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value

**Comment by vitorhirota** [comment]
Olá @erduarte, 

Sobre seu erro, talvez a lib requests nao tenha sido completamente baixada para sua máquina. O erro está no seguinte ImportError:

```
File "/storage/.xbmc/addons/script.module.requests/lib/requests/packages/charade/init.py", line 22, in detect
from . import universaldetector
File "/storage/.xbmc/addons/script.module.requests/lib/requests/packages/charade/universaldetector.py", line 29, in from . import constants
ImportError: cannot import name constants
```

Como pode ver no git da lib, o arquivo constants existe: https://github.com/beenje/script.module.requests/blob/master/lib/requests/packages/charade/

Verifique no caminho da lib se o arquivo existe, e caso não exista, baixe-o.
O XBMC deveria cuidar disso sozinho, mas pode ser que tenha ocorrido algum erro.

Sobre desenvolvimento de addons, eles sao desenvolvidos através da [interface python do XBMC](http://wiki.xbmc.org/index.php?title=Add-on_development). Mais info aqui e eu utilizo o framework [xbmcswift2](https://github.com/jbeluch/xbmcswift2) para este addon.

Pegue uma idéia, de uma olhada em algum addon ja existente para se ter uma idéia da estrutura e mande ver. Se precisar de ajuda, estou a disposição.
